common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from pybo import views
from rest_framework import routers
from pybo.views import MovieViewSet

router = routers.DefaultRouter() 
router.register('movies',MovieViewSet) # prefix = movies , viewset = MovieViewSet

urlpatterns = [
    re_path(r'^adminn/', admin.site.urls),
    re_path(r'^api',include(router.urls)),
    path("admin/", admin.site.urls),
    path("pybo/", include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('answer/vote/<int:answer_id>/', views.answer_vote, name='answer_vote'),
    path('question/vote/<int:question_id>/', views.question_vote, name='question_vote'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

templates/common/login.html
<link rel="stylesheet" href="../sass/login.css">


{% extends "base.html" %}
{% block content %}


<!--https://d3j8buaepzkvqi.cloudfront.net/mp4/Video_Preview.mp4-->

<div class="container-fluid main-container">


    <video id="background_video" style="width: 100%; height: 100vh; object-fit: cover; position: fixed; top: 0px; left: 0px; z-index: -1; user-select: auto;" muted="" poster="" playsinline="" autoplay="" loop="" preload="auto">
        <source src='https://d3j8buaepzkvqi.cloudfront.net/mp4/Video_Preview.mp4'  type="video/mp4" style="user-select: auto;" >
    </video>


    <div class="container" id="wc-container" style="user-select: auto;">

        <div class="row mobile-only" style="user-select: auto;">
            <div class="col-12" style="text-align: center; margin-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 50px; width: 100%; user-select: auto;">
                <h3 class="feature-heading mb-2 heading_mention pc-only" style="user-select: auto;"></h3>
            </div>
        </div>

        <div class="row" id="main_row" style="user-select: auto;">


            <!-- <div class="col-md-6 pc-only" style="text-align: left; margin-bottom: 0px; padding-left: 0px;"> -->

            <!-- <img class="featurette-image img-fluid mx-auto" id="main_image_1" src="https://d3j8buaepzkvqi.cloudfront.net/img/treatment.gif"alt=""> -->
            <!-- <video style="width: 100%; margin-top: 24px;" muted="" poster="https://d3j8buaepzkvqi.cloudfront.net/img/main-02_resized.png" playsinline="" autoplay="" loop="" preload="auto">
                <source src="https://d3j8buaepzkvqi.cloudfront.net/mp4/0304_main.mp4" type="video/mp4">
            </video> -->
            <!-- </div> -->

            <div class="col-lg-8 offset-lg-2 col-xl-4 offset-xl-4" style="padding: 0px; user-select: auto;">

                <div id="main_heading" style="padding-left: 10px;padding-right: 10px;background-color: rgba(255, 255, 255, 0.87);user-select: auto; border-radius: 1rem; box-shadow: 0 0 15px 1px rgb(0 0 0 / 40%); ">

                    <div class="row" style="padding-top: 2rem; user-select: auto;">
                        <div class="col-md-12 mb-3" style="text-align: center; user-select: auto;">

                            <h3 class="pc-only"  style="height: 25px; margin-bottom: 15px; user-select: auto;">DOG AND CAT</h3>
                            <h3 class="feature-heading mb-5 pc-only heading_mention" style="user-select: auto;">디지털 알렉산더의 모험</h3>
                            <h3 class="feature-heading mb-3 mobile-only" style="user-select: auto;">로그인</h3>
                        </div>
                        <div class="col-md-12" style="user-select: auto;"></div>
                    </div>




                    <div style="user-select: auto;">

                        <!-- <hr> -->

                        <div class="row" style="text-align: center; user-select: auto; " >
                            <div class="col-md-12" style="user-select: auto;">
                                <!-- <h3 class="feature-heading">로그인</h3> -->
                            </div>
                            <!-- <div class="col-md-8 offset-md-2" style="padding-left: 15px; padding-right: 15px;"> -->
                            <div class="col-md-12" style="padding-left: 15px; padding-right: 15px; user-select: auto;">
                                <form method="post" action="{% url 'common:login' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->

                                    {% include "form_errors.html" %}
                                    <div class="mb-3">
                                        <label for="username">사용자ID</label>
                                        <input type="text" class="form-control" name="username" id="username"
                                               value="{{ form.username.value|default_if_none:'' }}">
                                    </div>
                                    <div class="mb-3">
                                        <label for="password">비밀번호</label>
                                        <input type="password" class="form-control" name="password" id="password"
                                               value="{{ form.password.value|default_if_none:'' }}">
                                    </div>
                                    <button type="submit" class="btn btn-primary">로그인</button>
                                </form>
<!--                                <form method="POST" id="login_submit_form" style="user-select: auto;">-->
<!--                                    <input type="hidden" name="csrfmiddlewaretoken" value="WcFuNSPa74NdWQZHycsmlTgYxq7Yq5KF5ZxQ4xiSsKX08UMLxfIN75jkuocXaqFR" style="user-select: auto;">-->


<!--                                    <div id="div_id_email" class="form-group" style="user-select: auto;">-->
<!--                                        <label for="id_email" class="control-label  requiredField" style="user-select: auto;">-->
<!--                                        이메일<span class="asteriskField" style="user-select: auto;">*</span>-->
<!--                                        </label>-->

<!--                                        <div class="controls " style="user-select: auto;">-->
<!--                                        <input type="text" name="email" autofocus="" autocapitalize="off" class="textinput textInput form-control" required="" id="id_email" style="user-select: auto;">-->
<!--                                        </div>-->
<!--                                    </div>-->

<!--                                    <div id="div_id_password" class="form-group" style="user-select: auto;">-->
<!--                                        <label for="id_password" class="control-label  requiredField" style="user-select: auto;">-->
<!--                                        비밀번호<span class="asteriskField" style="user-select: auto;">*</span>-->
<!--                                        </label> <div class="controls " style="user-select: auto;">-->
<!--                                        <input type="password" name="password" class="textinput textInput form-control" required="" id="id_password" style="user-select: auto;">-->
<!--                                    </div>-->
<!--                                    </div>-->

<!--                                    <input type="hidden" id="next_url" name="next" value="" style="user-select: auto;">-->
<!--                                    <input type="hidden" id="id_msg_listen" name="msg_listen" value="" style="user-select: auto;">-->
<!--                                    <input type="hidden" id="id_msg_platform" name="msg_platform" value="" style="user-select: auto;">-->
<!--                                    <input type="button" class="btn btn-hover color-3 btn-block" id="login_submit" value="로그인" style="user-select: auto;">-->
<!--                                </form>-->
                                <br style="user-select: auto;">
                                <p style="user-select: auto;"> <a href="/ko/accounts/password/reset/" style="user-select: auto;">비밀번호를 잊으셨나요? </a>
                                </p>
                            </div>

                            <div class="col-md-12" id="footer_login" style="padding-left: 0px; padding-right: 0px; user-select: auto;">
                                <!-- <hr> -->
                                <p style="margin-top: 8px; user-select: auto;">아직 dog and cat 회원이 아니신가요 쿠헼헼?
                                   <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                                </p>
                            </div>


                        </div>

                        <hr style="margin-top: 0px; user-select: auto;">

                        <p class="pc-only app_banner" style="justify-content: center; display: flex; user-select: auto;">앱을 다운로드하세요.</p>

                        <div class="row main-buttons app_banner" style="justify-content: center; display: flex; user-select: auto; ">

                            <a class="" href="https://play.google.com/store/apps/details?id=com.assemblecircle.webceph" style=" user-select: auto; ">
                                <img alt="Available on Google Play" class="Rt8TI " src="https://d3j8buaepzkvqi.cloudfront.net/img/playstore.png" style="height: 40px; user-select: auto;">
                            </a>
                            <a class="" href="https://apps.apple.com/app/webceph/id1534844081" style="user-select: auto;">
                                <img alt="Available on the App Store" class="Rt8TI " src="https://d3j8buaepzkvqi.cloudfront.net/img/appstore.png" style="height: 40px; user-select: auto;">
                            </a>
                        </div>

                        <p class="company-copyright" style="text-align: center; margin-top: 20px; padding-bottom: 40px; user-select: auto;">AssembleCircle Corporation © 2022 </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}